// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Office struct {
	Name  string `json:"name"`
	Floor int    `json:"floor"`
}

type User struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}
